application: 3d-web-player
version: master
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "601s"

handlers:

- url: /static/
  static_dir: static/dist/
  application_readable: true
  secure: always

- url: /data/
  static_dir: data/
  secure: always

- url: /.*
  secure: always

skip_files:
    - README.md
    - static/src*
    - package.json
    - bower.json
    - node_modules
    - bower_components
    - gulp*
    - scripts/*
    - \.idea
    - \.editorconfig
    - \.eslintrc
    - \.sass-lint.yml
    - \.storage.*
    - \.git
    - (.*)\.pyc
    - (.*).DS_Store
